services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cache_lab
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d cache_lab"]
      interval: 3s
      timeout: 3s
      retries: 30
    mem_limit: 512m
    cpus: 1.0

  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 30
    mem_limit: 512m
    cpus: 1.0
